### ISSUE TITLE
[fluorine] mac test_salt_contains_function test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1219]
the test `integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function` is failing on mac sierra and highsierra. 

https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/61/
https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/61/

**Comment by dwoz** [comment]
I have not seen this fail in a while. I think it has been fixed.

**Comment by dwoz** [comment]
Looks like this is still failing:

https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-highsierra-py2/lastCompletedBuild/testReport/integration.states.test_renderers/TestJinjaRenderer/test_salt_contains_function/

**Comment by Ch3LL** [comment]
https://github.com/saltstack/salt/pull/51145

**Comment by Ch3LL** [comment]
i believe its still failing even with the PR above https://jenkinsci.saltstack.com/job/2019.2.0.rc1/job/salt-mac-sierra-py2/9/

**Comment by waynew** [comment]
I dug into this a little bit and I'm *pretty* sure it's happening due to the minion failing to start. If you run:

```
python runtests.py --interactive
```

then pop up a new terminal and run

```
salt -c /tmp/salt-tests-tmpdir/config/ minion state.sls jinja_dot_notation
```

It works and the result is True, as expected.

On the other hand, when I just run the test:

```
python runtests.py -n integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function; say done
```

I get this output:

```
Starting integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objc[8622]: +[NSValue initialize] may have been in progress in another thread when fork() was called.
objc[8622]: +[NSValue initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

So it looks like something is getting borked *somewhere* - the test works when manually running it, just not on autopilot 🤷‍♂️

**Comment by waynew** [comment]
Oh, also, it's definitely something going on with the Mac libs, because I can run the same test within a Docker (ubuntu 18.04) container and it works A-OK

**Comment by Ch3LL** [comment]
Issue moved to [saltstack/salt #51884](https://github.com/saltstack/salt/issues/51884) via [**ZenHub**](https://www.zenhub.com/)
