### ISSUE TITLE
[2016.11] Fix unit.crypt_test.CryptTestCase.test_sign_message

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#438]
The test `unit.crypt_test.CryptTestCase.test_sign_message` is failing with message

```
Error Message

'long' object is unsubscriptable
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/crypt_test.py", line 106, in test_sign_message
    self.assertEqual(SIG, salt.crypt.sign_message('/keydir/keyname.pem', MSG))
  File "/testing/salt/crypt.py", line 179, in sign_message
    return signer.sign(SHA.new(message))
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Signature/pkcs1_15.py", line 118, in sign
    m_int = self._key._decrypt(em_int)
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/RSA.py", line 228, in _decrypt
    (ciphertext,) = c[:1]  # HACK - We should use the previous line
TypeError: 'long' object is unsubscriptable
```

I was able to track down the first bad commit to be this merge forward: e685858269 

I believe in that merge forward it was this commit https://github.com/saltstack/salt/pull/41750/commits/e44673cdae485cb4ba062170dc63bc7937d841b8 that caused the issue, because it edited the sign_message function in salt/crypt.py

What I found is that when pycryptodome is installed we see this error. When only python-crypto is installed i do not see this error.

**Comment by Ch3LL** [comment]
Okay i think the issue is the test and when both pycryptodome and pycrypto exist. Working on a fix now

**Comment by Ch3LL** [comment]
Okay ti believe the  issue is related to having both pycryptodome and pycrypto on the same box. 

On this commit: 2e4a0633dac40143c632487c4742ae6502416f17 which is right before the bad commit this call `m_int = self._key._decrypt(em_int)` in `/usr/lib64/python2.6/site-packages/Cryptodome/Signature/pkcs1_15.py` ends up using the file `/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py` which is to be expected. 

On the bad commit e685858269629f6a8c9f0c91e630be5b76f98e70 the same call in the pkcs1_15.py file ends up calling this file instead: `:/usr/lib64/python2.6/site-packages/Crypto/PublicKey/RSA.py` which throws the type error on this `(ciphertext,) = c[:1]` 

Working on a PR to ensure we are only using pycryptodome or pycrypto during the test

**Comment by rallytime** [comment]
@Ch3LL Is this fixed now with the above PR?

**Comment by Ch3LL** [comment]
I can't completely confirm because it looks like cent6 is not bootstrapping properly. I'll close for now because I'm pretty certain this will resolve the issue. And will re-open if I find its still broken.
